### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by evanerichards** [nvmax/FluxComfyDiscordbot#1]
I followed all the instructions for install and when I run the bot I get this error immediately:

E:\FluxComfyDiscordbot>E:\FluxComfyDiscordbot\bot.py
Traceback (most recent call last):
  File "E:\FluxComfyDiscordbot\bot.py", line 6, in <module>
    from config import (
  File "E:\FluxComfyDiscordbot\config.py", line 16, in <module>
    BOT_MANAGER_ROLE_ID = int(os.getenv('BOT_MANAGER_ROLE_ID'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Any thoughts?

**Comment by evanerichards** [comment]
I'm not sure you can leave the bot manager ID blank. Once I added my bot ID in there everything seems to work fine.

**Comment by nvmax** [comment]
I know you closed this but I will double check the bot manager id and verify it can be left blank if not I will resolve it.. Thanks for the feed back.
